from __future__ import annotations

import json
from pathlib import Path

from .models import BacktestConfig, StrategySpec


def export_strategy_json(strategy: StrategySpec, config: BacktestConfig) -> str:
    return json.dumps(
        {"schema_version": 1, "strategy": strategy.to_dict(), "backtest": config.__dict__},
        indent=2,
        sort_keys=True,
    )


def write_export_bundle(
    directory: str | Path, strategy: StrategySpec, config: BacktestConfig
) -> tuple[Path, Path]:
    target = Path(directory)
    target.mkdir(parents=True, exist_ok=True)
    stem = _safe_name(strategy.strategy_id)
    json_path = target / f"{stem}.json"
    mq5_path = target / f"{stem}.mq5"
    json_path.write_text(export_strategy_json(strategy, config), encoding="utf-8")
    mq5_path.write_text(export_mql5(strategy, config), encoding="utf-8")
    return json_path, mq5_path


def export_mql5(strategy: StrategySpec, config: BacktestConfig) -> str:
    """Generate an auditable MT5 EA for the two MVP strategy families."""

    family = 0 if strategy.family == "ema_cross" else 1
    fast = int(strategy.params.get("fast", 20))
    slow = int(strategy.params.get("slow", 100))
    window = int(strategy.params.get("window", 20))
    atr_period = int(strategy.params.get("atr_period", 14))
    stop_atr = float(strategy.params.get("stop_atr", 2.0))
    target_atr = float(strategy.params.get("target_atr", 3.0))
    direction = {"long": 1, "short": -1, "both": 0}[strategy.direction]
    replacements = {
        "__STRATEGY_ID__": strategy.strategy_id,
        "__FAMILY__": str(family),
        "__FAST__": str(fast),
        "__SLOW__": str(slow),
        "__WINDOW__": str(window),
        "__ATR_PERIOD__": str(atr_period),
        "__STOP_ATR__": f"{stop_atr:.8g}",
        "__TARGET_ATR__": f"{target_atr:.8g}",
        "__DIRECTION__": str(direction),
        "__RISK_PERCENT__": f"{config.risk_fraction * 100:.8g}",
        "__MAX_DD_PERCENT__": f"{config.max_drawdown * 100:.8g}",
    }
    code = _MQL5_TEMPLATE
    for key, value in replacements.items():
        code = code.replace(key, value)
    return code


def _safe_name(value: str) -> str:
    return "".join(character if character.isalnum() or character in "-_" else "_" for character in value)


_MQL5_TEMPLATE = r'''// Generated by Strategy QuANT v0.1
// Strategy: __STRATEGY_ID__
// Review and compile in MetaEditor; validate against broker symbol settings before use.
#property strict
#include <Trade/Trade.mqh>

CTrade trade;
input long   InpMagic          = 26081001;
input int    InpFamily         = __FAMILY__; // 0 EMA cross, 1 breakout
input int    InpFastEMA        = __FAST__;
input int    InpSlowEMA        = __SLOW__;
input int    InpBreakoutBars   = __WINDOW__;
input int    InpATRPeriod      = __ATR_PERIOD__;
input double InpStopATR        = __STOP_ATR__;
input double InpTargetATR      = __TARGET_ATR__;
input int    InpDirection      = __DIRECTION__; // 1 long, -1 short, 0 both
input double InpRiskPercent    = __RISK_PERCENT__;
input double InpMaxDDPercent   = __MAX_DD_PERCENT__;
input int    InpDeviationPts   = 20;

int fastHandle = INVALID_HANDLE;
int slowHandle = INVALID_HANDLE;
int atrHandle = INVALID_HANDLE;
datetime lastBar = 0;
double peakEquity = 0.0;

int OnInit()
{
   trade.SetExpertMagicNumber(InpMagic);
   trade.SetDeviationInPoints(InpDeviationPts);
   atrHandle = iATR(_Symbol, PERIOD_CURRENT, InpATRPeriod);
   if(InpFamily == 0)
   {
      fastHandle = iMA(_Symbol, PERIOD_CURRENT, InpFastEMA, 0, MODE_EMA, PRICE_CLOSE);
      slowHandle = iMA(_Symbol, PERIOD_CURRENT, InpSlowEMA, 0, MODE_EMA, PRICE_CLOSE);
   }
   peakEquity = AccountInfoDouble(ACCOUNT_EQUITY);
   if(atrHandle == INVALID_HANDLE || (InpFamily == 0 && (fastHandle == INVALID_HANDLE || slowHandle == INVALID_HANDLE)))
      return INIT_FAILED;
   return INIT_SUCCEEDED;
}

void OnDeinit(const int reason)
{
   if(fastHandle != INVALID_HANDLE) IndicatorRelease(fastHandle);
   if(slowHandle != INVALID_HANDLE) IndicatorRelease(slowHandle);
   if(atrHandle != INVALID_HANDLE) IndicatorRelease(atrHandle);
}

bool NewBar()
{
   datetime current = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(current == 0 || current == lastBar) return false;
   lastBar = current;
   return true;
}

double BufferValue(const int handle, const int shift)
{
   double values[1];
   if(CopyBuffer(handle, 0, shift, 1, values) != 1) return EMPTY_VALUE;
   return values[0];
}

int GetSignal()
{
   if(InpFamily == 0)
   {
      double fast = BufferValue(fastHandle, 1);
      double slow = BufferValue(slowHandle, 1);
      if(fast == EMPTY_VALUE || slow == EMPTY_VALUE) return 0;
      if(fast > slow) return 1;
      if(fast < slow) return -1;
      return 0;
   }
   double highs[], lows[];
   ArraySetAsSeries(highs, true);
   ArraySetAsSeries(lows, true);
   if(CopyHigh(_Symbol, PERIOD_CURRENT, 2, InpBreakoutBars, highs) != InpBreakoutBars) return 0;
   if(CopyLow(_Symbol, PERIOD_CURRENT, 2, InpBreakoutBars, lows) != InpBreakoutBars) return 0;
   double close1 = iClose(_Symbol, PERIOD_CURRENT, 1);
   if(close1 > highs[ArrayMaximum(highs)]) return 1;
   if(close1 < lows[ArrayMinimum(lows)]) return -1;
   return 0;
}

double RiskVolume(const double stopDistance)
{
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double step = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   double minimum = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maximum = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   if(stopDistance <= 0 || tickSize <= 0 || tickValue <= 0 || step <= 0) return 0;
   double riskMoney = AccountInfoDouble(ACCOUNT_EQUITY) * InpRiskPercent / 100.0;
   double raw = riskMoney / ((stopDistance / tickSize) * tickValue);
   double volume = MathFloor(raw / step) * step;
   return MathMax(minimum, MathMin(maximum, volume));
}

void OnTick()
{
   if(!NewBar()) return; // signal on closed bar, execution on the next bar
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   peakEquity = MathMax(peakEquity, equity);
   if(peakEquity > 0 && (peakEquity - equity) / peakEquity * 100.0 >= InpMaxDDPercent) return;

   int signal = GetSignal();
   if((InpDirection == 1 && signal < 0) || (InpDirection == -1 && signal > 0)) signal = 0;
   if(signal == 0) return;

   if(PositionSelect(_Symbol))
   {
      long type = PositionGetInteger(POSITION_TYPE);
      int held = type == POSITION_TYPE_BUY ? 1 : -1;
      if(held == signal) return;
      if(!trade.PositionClose(_Symbol)) return;
   }

   double atr = BufferValue(atrHandle, 1);
   if(atr == EMPTY_VALUE || atr <= 0) return;
   double distance = atr * InpStopATR;
   double volume = RiskVolume(distance);
   if(volume <= 0) return;
   int digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
   if(signal > 0)
   {
      double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      trade.Buy(volume, _Symbol, 0, NormalizeDouble(ask - distance, digits),
                NormalizeDouble(ask + atr * InpTargetATR, digits), "Strategy QuANT");
   }
   else
   {
      double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      trade.Sell(volume, _Symbol, 0, NormalizeDouble(bid + distance, digits),
                 NormalizeDouble(bid - atr * InpTargetATR, digits), "Strategy QuANT");
   }
}
'''

